### ISSUE TITLE
Make failure.

### ISSUE THREAD

**Issue by Achaean** [BR903/cgames#6]
**Hi!** :-)

Make returns this error message:
```
userio.c:41:17: fatal error: gpm.h: No such file or directory
 #include <gpm.h>
                 ^
compilation terminated.
<builtin>: recipe for target 'userio.o' failed
make[1]: *** [userio.o] Error 1
make[1]: Leaving directory '/home/giorgos/TEMPG/cgames-master/cmines'
Makefile:28: recipe for target 'cmines-build' failed
make: *** [cmines-build] Error 2
```
Now what? :-)
I'm on Debian Jessie (oldstable) x64 KDE.
PS. libgmp3-dev is already installed.

**Comment by BR903** [comment]
I tried looking at https://packages.debian.org/jessie/libgpm3-dev but there's nothing there. I do find https://packages.debian.org/jessie/libgpm-dev though, which references libgpm2. I don't see a reference to libgpm3 in jessie.

I suspect that the code will build with libgpm2 (and libgpm-dev). I don't know how libgpm3-dev is different though.

**Comment by Achaean** [comment]
Indeed! Installing libgpm-dev, solved the problem.
**THANKS** BR903!!! :-)
