### ISSUE TITLE
Running problem (without ncurses version).

### ISSUE THREAD

**Issue by Achaean** [BR903/cgames#7]
Now another one! :-)
Csokoban and Cblocks are failing to run (without ncurses).
```
>csokoban

Original.txt: Inappropriate ioctl for device
csokoban: Failed to initialize terminal.
>
```
and
```
>cblocks
Classics.txt: Inappropriate ioctl for device

cblocks: Failed to initialize terminal.
>
```
Ncurses version runs flawlessly.
Personally I prefer the ncurses version, but I'm reporting it anyway.

**Comment by BR903** [comment]
Did you run them in the Linux console? The non-ncurses versions only work on the Linux console (thus the "c" in the name cgames).

**Comment by Achaean** [comment]
Ooops! Mea Culpa! :-)

I ran it on Yakuake.
Switching (ctrl-alt-f1) to another TTY, solved the problem.
